//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NlogData
{
    using System;
    using System.Collections.Generic;
    
    public partial class NLogConfirm
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public string ItemText { get; set; }
        public string SpendTime { get; set; }
        public string Tag { get; set; }
    }
}
